theme: jekyll-theme-minimal
title: Brother - Jeedom plugin for Bother printers
description: Jeedom plugin to retrieve information from Brother printers
show_downloads: true
logo: /assets/images/logo.png